drop extension if exists "pg_net";


  create table "public"."video" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "update_at" timestamp without time zone,
    "title" text,
    "description" text,
    "youtube_id" character varying,
    "tags" json,
    "last_seen" timestamp without time zone,
    "id_creator" uuid
      );


alter table "public"."video" enable row level security;


  create table "public"."view" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "id_video" bigint,
    "id_user" uuid,
    "last_position_sec" bigint
      );


alter table "public"."view" enable row level security;

CREATE UNIQUE INDEX video_pkey ON public.video USING btree (id);

CREATE UNIQUE INDEX view_pkey ON public.view USING btree (id);

alter table "public"."video" add constraint "video_pkey" PRIMARY KEY using index "video_pkey";

alter table "public"."view" add constraint "view_pkey" PRIMARY KEY using index "view_pkey";

alter table "public"."video" add constraint "video_id_video_fkey" FOREIGN KEY (id_creator) REFERENCES auth.users(id) not valid;

alter table "public"."video" validate constraint "video_id_video_fkey";

alter table "public"."view" add constraint "view_id_user_fkey" FOREIGN KEY (id_user) REFERENCES auth.users(id) not valid;

alter table "public"."view" validate constraint "view_id_user_fkey";

alter table "public"."view" add constraint "view_id_video_fkey" FOREIGN KEY (id_video) REFERENCES public.video(id) not valid;

alter table "public"."view" validate constraint "view_id_video_fkey";

grant delete on table "public"."video" to "anon";

grant insert on table "public"."video" to "anon";

grant references on table "public"."video" to "anon";

grant select on table "public"."video" to "anon";

grant trigger on table "public"."video" to "anon";

grant truncate on table "public"."video" to "anon";

grant update on table "public"."video" to "anon";

grant delete on table "public"."video" to "authenticated";

grant insert on table "public"."video" to "authenticated";

grant references on table "public"."video" to "authenticated";

grant select on table "public"."video" to "authenticated";

grant trigger on table "public"."video" to "authenticated";

grant truncate on table "public"."video" to "authenticated";

grant update on table "public"."video" to "authenticated";

grant delete on table "public"."video" to "service_role";

grant insert on table "public"."video" to "service_role";

grant references on table "public"."video" to "service_role";

grant select on table "public"."video" to "service_role";

grant trigger on table "public"."video" to "service_role";

grant truncate on table "public"."video" to "service_role";

grant update on table "public"."video" to "service_role";

grant delete on table "public"."view" to "anon";

grant insert on table "public"."view" to "anon";

grant references on table "public"."view" to "anon";

grant select on table "public"."view" to "anon";

grant trigger on table "public"."view" to "anon";

grant truncate on table "public"."view" to "anon";

grant update on table "public"."view" to "anon";

grant delete on table "public"."view" to "authenticated";

grant insert on table "public"."view" to "authenticated";

grant references on table "public"."view" to "authenticated";

grant select on table "public"."view" to "authenticated";

grant trigger on table "public"."view" to "authenticated";

grant truncate on table "public"."view" to "authenticated";

grant update on table "public"."view" to "authenticated";

grant delete on table "public"."view" to "service_role";

grant insert on table "public"."view" to "service_role";

grant references on table "public"."view" to "service_role";

grant select on table "public"."view" to "service_role";

grant trigger on table "public"."view" to "service_role";

grant truncate on table "public"."view" to "service_role";

grant update on table "public"."view" to "service_role";


  create policy "delete own video"
  on "public"."video"
  as permissive
  for delete
  to public
using ((auth.uid() = id_creator));



  create policy "insert own video"
  on "public"."video"
  as permissive
  for insert
  to public
with check ((auth.uid() = id_creator));



  create policy "public read video"
  on "public"."video"
  as permissive
  for select
  to public
using (true);



  create policy "public read"
  on "public"."video"
  as permissive
  for select
  to public
using (true);



  create policy "update own video"
  on "public"."video"
  as permissive
  for update
  to public
using ((auth.uid() = id_creator));



  create policy "insert own view"
  on "public"."view"
  as permissive
  for insert
  to public
with check ((auth.uid() = id_user));



  create policy "read own view"
  on "public"."view"
  as permissive
  for select
  to public
using ((auth.uid() = id_user));



  create policy "update own view"
  on "public"."view"
  as permissive
  for update
  to public
using ((auth.uid() = id_user));



